import { Product } from "@/types/types";

const products: Product[] = [
  {
    id: 1,
    name: "Grifo",
    image: "/products/Grifo.png",
    description: "Stylish cafe chair",
    price: 2500000,
    favorite: false,
    discount: true,
    discountPercentage: 20,
    new: false,
  },
  {
    id: 2,
    name: "Leviosa",
    image: "/products/Leviosa.png",
    description: "Stylish cafe chair",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: false,
  },
  {
    id: 3,
    name: "Lolito",
    image: "/products/Lolito.png",
    description: "Luxury big sofa",
    price: 2500000,
    favorite: false,
    discount: true,
    discountPercentage: 50,
    new: false,
  },
  {
    id: 4,
    name: "Muggo",
    image: "/products/Muggo.png",
    description: "Outdoor bar table and stool",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
  },
  {
    id: 5,
    name: "Pingky",
    image: "/products/Pingky.png",
    description: "Night lamp",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
  },
  {
    id: 6,
    name: "Potty",
    image: "/products/Potty.png",
    description: "Small mug",
    price: 2500000,
    favorite: false,
    discount: true,
    discountPercentage: 80,
    new: false,
  },
  {
    id: 7,
    name: "Respira",
    image: "/products/Respira.png",
    description: "Cute bed set",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: false,
  },
  {
    id: 8,
    name: "Syltherine",
    image: "/products/Syltherine.png",
    description: "Minimalist flower pot",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
  },
];

export function GET() {
  return Response.json(products, { status: 200 });
}
