import { Product } from "@/types/types";

export const menuItem: string[] = ["Home", "Shop", "About", "Contact"];

export const products: Product[] = [
  {
    id: 1,
    name: "Grifo",
    image: "/products/Grifo.png",
    description: "Stylish cafe chair",
    price: 3500000,
    favorite: false,
    discount: true,
    discountPercentage: 20,
    new: false,
    category: "sleeping area",
  },
  {
    id: 2,
    name: "Leviosa",
    image: "/products/Leviosa.png",
    description: "Stylish cafe chair",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: false,
    category: "tables and chairs",
  },
  {
    id: 3,
    name: "Lolito",
    image: "/products/Lolito.png",
    description: "Luxury big sofa",
    price: 4500000,
    favorite: false,
    discount: true,
    discountPercentage: 50,
    new: false,
    category: "sleeping area",
  },
  {
    id: 4,
    name: "Muggo",
    image: "/products/Muggo.png",
    description: "Outdoor bar table and stool",
    price: 5600000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "tables and chairs",
  },
  {
    id: 5,
    name: "Pingky",
    image: "/products/Pingky.png",
    description: "Night lamp",
    price: 1300000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "tables and chairs",
  },
  {
    id: 6,
    name: "Potty",
    image: "/products/Potty.png",
    description: "Small mug",
    price: 6700000,
    favorite: false,
    discount: true,
    discountPercentage: 80,
    new: false,
    category: "sleeping area",
  },
  {
    id: 7,
    name: "Respira",
    image: "/products/Respira.png",
    description: "Cute bed set",
    price: 2400000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: false,
    category: "sleeping area",
  },
  {
    id: 8,
    name: "Syltherine",
    image: "/products/Syltherine.png",
    description: "Minimalist flower pot",
    price: 3300000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "sleeping area",
  },
  {
    id: 9,
    name: "BedRoom - 1",
    image: "/products/BedRoom-1.png",
    description: "Inner Peace",
    price: 4700000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
  {
    id: 10,
    name: "BedRoom - 2",
    image: "/products/BedRoom-2.png",
    description: "Inner Peace",
    price: 3900000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
  {
    id: 11,
    name: "BedRoom - 3",
    image: "/products/Rectangle 43.png",
    description: "Inner Peace",
    price: 9800000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
  {
    id: 12,
    name: "BedRoom - 4",
    image: "/products/Rectangle 45.png",
    description: "Inner Peace",
    price: 7600000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
  {
    id: 13,
    name: "Respira 35",
    image: "/products/Rectangle 35.png",
    description: "Inner Peace",
    price: 3200000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "sleeping area",
  },
  {
    id: 14,
    name: "Respira 36",
    image: "/products/Rectangle 36.png",
    description: "Inner Peace",
    price: 4600000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "sofas and armchairs",
  },
  {
    id: 16,
    name: "Respira 37",
    image: "/products/Rectangle 37.png",
    description: "Inner Peace",
    price: 7600000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "sleeping area",
  },
  {
    id: 17,
    name: "Respira 38",
    image: "/products/Rectangle 38.png",
    description: "Inner Peace",
    price: 1300000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "tables and chairs",
  },
  {
    id: 18,
    name: "Respira 39",
    image: "/products/Rectangle 39.png",
    description: "Inner Peace",
    price: 5800000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "sofas and armchairs",
  },

  {
    id: 19,
    name: "Respira 40",
    image: "/products/Rectangle 40.png",
    description: "Inner Peace",
    price: 8200000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "tables and chairs",
  },
  {
    id: 20,
    name: "Respira 41",
    image: "/products/Rectangle 41.png",
    description: "Inner Peace",
    price: 7300000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "tables and chairs",
  },
  {
    id: 21,
    name: "Respira 43",
    image: "/products/Rectangle 43.png",
    description: "Inner Peace",
    price: 4800000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "sofas and armchairs",
  },
  {
    id: 22,
    name: "Respira 44",
    image: "/products/Rectangle 44.png",
    description: "Inner Peace",
    price: 2100000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "tables and chairs",
  },
  {
    id: 23,
    name: "Respira 45",
    image: "/products/Rectangle 45.png",
    description: "Inner Peace",
    price: 1200000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "sofas and armchairs",
  },
];
