<<<<<<< HEAD
import { Product } from "@/types/types";

export const menuItem: string[] = ["Home", "Shop", "About", "Contact"];

export const products: Product[] = [
  {
    id: 1,
    name: "Grifo",
    image: "/products/Grifo.png",
    description: "Stylish cafe chair",
    price: 2500000,
    favorite: false,
    discount: true,
    discountPercentage: 20,
    new: false,
    category: "",
  },
  {
    id: 2,
    name: "Leviosa",
    image: "/products/Leviosa.png",
    description: "Stylish cafe chair",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: false,
    category: "",
  },
  {
    id: 3,
    name: "Lolito",
    image: "/products/Lolito.png",
    description: "Luxury big sofa",
    price: 2500000,
    favorite: false,
    discount: true,
    discountPercentage: 50,
    new: false,
    category: "",
  },
  {
    id: 4,
    name: "Muggo",
    image: "/products/Muggo.png",
    description: "Outdoor bar table and stool",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "",
  },
  {
    id: 5,
    name: "Pingky",
    image: "/products/Pingky.png",
    description: "Night lamp",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "",
  },
  {
    id: 6,
    name: "Potty",
    image: "/products/Potty.png",
    description: "Small mug",
    price: 2500000,
    favorite: false,
    discount: true,
    discountPercentage: 80,
    new: false,
    category: "",
  },
  {
    id: 7,
    name: "Respira",
    image: "/products/Respira.png",
    description: "Cute bed set",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: false,
    category: "",
  },
  {
    id: 8,
    name: "Syltherine",
    image: "/products/Syltherine.png",
    description: "Minimalist flower pot",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "",
  },
  {
    id: 9,
    name: "BedRoom - 1",
    image: "/products/BedRoom-1.png",
    description: "Inner Peace",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
  {
    id: 10,
    name: "BedRoom - 2",
    image: "/products/BedRoom-2.png",
    description: "Inner Peace",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
  {
    id: 11,
    name: "BedRoom - 3",
    image: "/products/Rectangle 43.png",
    description: "Inner Peace",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
  {
    id: 12,
    name: "BedRoom - 4",
    image: "/products/Rectangle 45.png",
    description: "Inner Peace",
    price: 2500000,
    favorite: false,
    discount: false,
    discountPercentage: 0,
    new: true,
    category: "room",
  },
];
=======
export const menuItem: string[] = ["home", "shop", "about", "contact"];
>>>>>>> navbar
